[package]
name = "mastodon-twitter-sync"
version = "0.1.0"
authors = ["Klaus Purer <klaus.purer@gmail.com>"]

[dependencies]
chrono = ">=0.4.0"
dissolve = ">=0.2.2"
egg-mode = ">=0.11"
mammut = ">=0.9"
regex = ">=0.2.2"
serde = ">=1.0"
serde_derive = ">=1.0.19"
tokio-core = ">=0.1.10"
toml = ">=0.4.5"

[dev-dependencies]
serde_json = ">=1.0.6"

[patch.crates-io]
mammut = { git = "https://github.com/klausi/Mammut", branch = "klausi" }
#mammut = { path = "../Mammut" }
